// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/create_project.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/create_project.go -destination=./mocks/mock_create_project.go -package=resthandlmocks
//

// Package resthandlmocks is a generated GoMock package.
package resthandlmocks

import (
	context "context"
	createmodel "projectservice/internal/usecase/models/createproject"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateProjectUsecase is a mock of CreateProjectUsecase interface.
type MockCreateProjectUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateProjectUsecaseMockRecorder
	isgomock struct{}
}

// MockCreateProjectUsecaseMockRecorder is the mock recorder for MockCreateProjectUsecase.
type MockCreateProjectUsecaseMockRecorder struct {
	mock *MockCreateProjectUsecase
}

// NewMockCreateProjectUsecase creates a new mock instance.
func NewMockCreateProjectUsecase(ctrl *gomock.Controller) *MockCreateProjectUsecase {
	mock := &MockCreateProjectUsecase{ctrl: ctrl}
	mock.recorder = &MockCreateProjectUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateProjectUsecase) EXPECT() *MockCreateProjectUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateProjectUsecase) Execute(ctx context.Context, in *createmodel.CreateProjectInput) (*createmodel.CreateProjectOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*createmodel.CreateProjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateProjectUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateProjectUsecase)(nil).Execute), ctx, in)
}
