// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/userservice/user.proto

package userservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIdBySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdBySessionRequest) Reset() {
	*x = GetIdBySessionRequest{}
	mi := &file_proto_userservice_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdBySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdBySessionRequest) ProtoMessage() {}

func (x *GetIdBySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdBySessionRequest.ProtoReflect.Descriptor instead.
func (*GetIdBySessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetIdBySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetIdBySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdBySessionResponse) Reset() {
	*x = GetIdBySessionResponse{}
	mi := &file_proto_userservice_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdBySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdBySessionResponse) ProtoMessage() {}

func (x *GetIdBySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdBySessionResponse.ProtoReflect.Descriptor instead.
func (*GetIdBySessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_userservice_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdBySessionResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_userservice_user_proto protoreflect.FileDescriptor

const file_proto_userservice_user_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/userservice/user.proto\x12\x10userserviceproto\"5\n" +
	"\x15GetIdBySessionRequest\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\"0\n" +
	"\x16GetIdBySessionResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId2r\n" +
	"\vUserService\x12c\n" +
	"\x0eGetIdBySession\x12'.userserviceproto.GetIdBySessionRequest\x1a(.userserviceproto.GetIdBySessionResponseB\x12Z\x10./;userservicev1b\x06proto3"

var (
	file_proto_userservice_user_proto_rawDescOnce sync.Once
	file_proto_userservice_user_proto_rawDescData []byte
)

func file_proto_userservice_user_proto_rawDescGZIP() []byte {
	file_proto_userservice_user_proto_rawDescOnce.Do(func() {
		file_proto_userservice_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userservice_user_proto_rawDesc), len(file_proto_userservice_user_proto_rawDesc)))
	})
	return file_proto_userservice_user_proto_rawDescData
}

var file_proto_userservice_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_userservice_user_proto_goTypes = []any{
	(*GetIdBySessionRequest)(nil),  // 0: userserviceproto.GetIdBySessionRequest
	(*GetIdBySessionResponse)(nil), // 1: userserviceproto.GetIdBySessionResponse
}
var file_proto_userservice_user_proto_depIdxs = []int32{
	0, // 0: userserviceproto.UserService.GetIdBySession:input_type -> userserviceproto.GetIdBySessionRequest
	1, // 1: userserviceproto.UserService.GetIdBySession:output_type -> userserviceproto.GetIdBySessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_userservice_user_proto_init() }
func file_proto_userservice_user_proto_init() {
	if File_proto_userservice_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userservice_user_proto_rawDesc), len(file_proto_userservice_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userservice_user_proto_goTypes,
		DependencyIndexes: file_proto_userservice_user_proto_depIdxs,
		MessageInfos:      file_proto_userservice_user_proto_msgTypes,
	}.Build()
	File_proto_userservice_user_proto = out.File
	file_proto_userservice_user_proto_goTypes = nil
	file_proto_userservice_user_proto_depIdxs = nil
}
