// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../repository/storage/storagerepo.go
//
// Generated by this command:
//
//	mockgen -source=./../../../repository/storage/storagerepo.go -destination=./mocks/mock_storage.go -package=getallmocks
//

// Package getallmocks is a generated GoMock package.
package getallmocks

import (
	context "context"
	projectdomain "projectservice/internal/domain/project"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepo is a mock of StorageRepo interface.
type MockStorageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepoMockRecorder
	isgomock struct{}
}

// MockStorageRepoMockRecorder is the mock recorder for MockStorageRepo.
type MockStorageRepoMockRecorder struct {
	mock *MockStorageRepo
}

// NewMockStorageRepo creates a new mock instance.
func NewMockStorageRepo(ctrl *gomock.Controller) *MockStorageRepo {
	mock := &MockStorageRepo{ctrl: ctrl}
	mock.recorder = &MockStorageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepo) EXPECT() *MockStorageRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorageRepo) Delete(ctx context.Context, ownerId, projectId uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ownerId, projectId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageRepoMockRecorder) Delete(ctx, ownerId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageRepo)(nil).Delete), ctx, ownerId, projectId)
}

// GetAll mocks base method.
func (m *MockStorageRepo) GetAll(ctx context.Context, ownerId uint32) ([]*projectdomain.ProjectDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, ownerId)
	ret0, _ := ret[0].([]*projectdomain.ProjectDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStorageRepoMockRecorder) GetAll(ctx, ownerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStorageRepo)(nil).GetAll), ctx, ownerId)
}

// Save mocks base method.
func (m *MockStorageRepo) Save(ctx context.Context, proj *projectdomain.ProjectDomain) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, proj)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockStorageRepoMockRecorder) Save(ctx, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorageRepo)(nil).Save), ctx, proj)
}

// UpdateName mocks base method.
func (m *MockStorageRepo) UpdateName(ctx context.Context, ownerId, projectId uint32, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateName", ctx, ownerId, projectId, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateName indicates an expected call of UpdateName.
func (mr *MockStorageRepoMockRecorder) UpdateName(ctx, ownerId, projectId, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateName", reflect.TypeOf((*MockStorageRepo)(nil).UpdateName), ctx, ownerId, projectId, newName)
}
