// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../repository/sessionvalidator/session_validator.go
//
// Generated by this command:
//
//	mockgen -source=./../../../repository/sessionvalidator/session_validator.go -destination=./mocks/mock_session_validator.go -package=middlewaremocks
//

// Package middlewaremocks is a generated GoMock package.
package middlewaremocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionValidator is a mock of SessionValidator interface.
type MockSessionValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionValidatorMockRecorder
	isgomock struct{}
}

// MockSessionValidatorMockRecorder is the mock recorder for MockSessionValidator.
type MockSessionValidatorMockRecorder struct {
	mock *MockSessionValidator
}

// NewMockSessionValidator creates a new mock instance.
func NewMockSessionValidator(ctrl *gomock.Controller) *MockSessionValidator {
	mock := &MockSessionValidator{ctrl: ctrl}
	mock.recorder = &MockSessionValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionValidator) EXPECT() *MockSessionValidatorMockRecorder {
	return m.recorder
}

// GetIdBySession mocks base method.
func (m *MockSessionValidator) GetIdBySession(ctx context.Context, sessionId string) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdBySession", ctx, sessionId)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdBySession indicates an expected call of GetIdBySession.
func (mr *MockSessionValidatorMockRecorder) GetIdBySession(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdBySession", reflect.TypeOf((*MockSessionValidator)(nil).GetIdBySession), ctx, sessionId)
}
