// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/registration.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/registration.go -destination=mocks/mock_registration.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	regmodel "userservice/internal/usecase/models/registration"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationUsecase is a mock of RegistrationUsecase interface.
type MockRegistrationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationUsecaseMockRecorder
	isgomock struct{}
}

// MockRegistrationUsecaseMockRecorder is the mock recorder for MockRegistrationUsecase.
type MockRegistrationUsecaseMockRecorder struct {
	mock *MockRegistrationUsecase
}

// NewMockRegistrationUsecase creates a new mock instance.
func NewMockRegistrationUsecase(ctrl *gomock.Controller) *MockRegistrationUsecase {
	mock := &MockRegistrationUsecase{ctrl: ctrl}
	mock.recorder = &MockRegistrationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationUsecase) EXPECT() *MockRegistrationUsecaseMockRecorder {
	return m.recorder
}

// RegUser mocks base method.
func (m *MockRegistrationUsecase) RegUser(ctx context.Context, in *regmodel.RegInput) (*regmodel.RegOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegUser", ctx, in)
	ret0, _ := ret[0].(*regmodel.RegOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegUser indicates an expected call of RegUser.
func (mr *MockRegistrationUsecaseMockRecorder) RegUser(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegUser", reflect.TypeOf((*MockRegistrationUsecase)(nil).RegUser), ctx, in)
}
