// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/login.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/login.go -destination=mocks/mock_login.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	logmodel "userservice/internal/usecase/models/login"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginUsecase is a mock of LoginUsecase interface.
type MockLoginUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUsecaseMockRecorder
	isgomock struct{}
}

// MockLoginUsecaseMockRecorder is the mock recorder for MockLoginUsecase.
type MockLoginUsecaseMockRecorder struct {
	mock *MockLoginUsecase
}

// NewMockLoginUsecase creates a new mock instance.
func NewMockLoginUsecase(ctrl *gomock.Controller) *MockLoginUsecase {
	mock := &MockLoginUsecase{ctrl: ctrl}
	mock.recorder = &MockLoginUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUsecase) EXPECT() *MockLoginUsecaseMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockLoginUsecase) Login(ctx context.Context, in *logmodel.LoginInput) (*logmodel.LoginOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, in)
	ret0, _ := ret[0].(*logmodel.LoginOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockLoginUsecaseMockRecorder) Login(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockLoginUsecase)(nil).Login), ctx, in)
}
