// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../repository/storage/storagerepo.go
//
// Generated by this command:
//
//	mockgen -source=./../../../repository/storage/storagerepo.go -destination=./mocks/mock_storage.go -package=createmocks
//

// Package createmocks is a generated GoMock package.
package createmocks

import (
	context "context"
	reflect "reflect"
	taskdomain "taskservice/internal/domain/task"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepo is a mock of StorageRepo interface.
type MockStorageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepoMockRecorder
	isgomock struct{}
}

// MockStorageRepoMockRecorder is the mock recorder for MockStorageRepo.
type MockStorageRepoMockRecorder struct {
	mock *MockStorageRepo
}

// NewMockStorageRepo creates a new mock instance.
func NewMockStorageRepo(ctrl *gomock.Controller) *MockStorageRepo {
	mock := &MockStorageRepo{ctrl: ctrl}
	mock.recorder = &MockStorageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepo) EXPECT() *MockStorageRepoMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockStorageRepo) Save(ctx context.Context, td *taskdomain.TaskDomain) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, td)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockStorageRepoMockRecorder) Save(ctx, td any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorageRepo)(nil).Save), ctx, td)
}
